/**
 * 非機密情報のデフォルト設定値
 * .envに記述されていた機微情報（APIキー等）以外の設定を定数化しています。
 */
export const GNOSIS_CONSTANTS = {
  // LLM Configuration
  LLM_SCRIPT_DEFAULT: 'services/local-llm/scripts/gemma4',
  BONSAI_SCRIPT_DEFAULT: 'services/local-llm/scripts/bonsai',
  LOCAL_LLM_PATH_DEFAULT: 'services/local-llm',

  // Review LLM (Non-sensitive)
  REVIEW_LLM_PROVIDER_DEFAULT: 'azure-openai',
  REVIEW_LLM_API_BASE_URL_DEFAULT: 'https://aoai-westus-ynoguchi.openai.azure.com',
  AZURE_OPENAI_MODEL_DEFAULT: 'gpt-5-4-mini',

  // Embedding
  EMBED_COMMAND_DEFAULT: 'services/embedding/.venv/bin/embed',
  EMBEDDING_DIMENSION_DEFAULT: 384,
  DEDUPE_THRESHOLD_DEFAULT: 0.9,
  EMBED_TIMEOUT_MS_DEFAULT: 30000,

  // Local LLM API
  LOCAL_LLM_API_BASE_URL_DEFAULT: 'http://127.0.0.1:44448',
  LOCAL_LLM_API_PATH_DEFAULT: '/v1/chat/completions',
  LOCAL_LLM_MODEL_DEFAULT: 'gemma-4-e4b-it',
  LOCAL_LLM_ENABLE_CLI_FALLBACK_DEFAULT: true,
  LOCAL_LLM_TIMEOUT_MS_DEFAULT: 180000,
  LOCAL_LLM_MAX_RETRIES_DEFAULT: 2,
  LOCAL_LLM_RETRY_DELAY_MS_DEFAULT: 300,

  // AWS Configuration
  AWS_REGION_DEFAULT: 'ap-northeast-1',
  BEDROCK_MODEL_ID_DEFAULT: 'anthropic.claude-sonnet-4-6',
  BEDROCK_INFERENCE_PROFILE_ID_DEFAULT: 'jp.anthropic.claude-sonnet-4-6',

  // Worker Configuration
  WORKER_TASK_TIMEOUT_MS_DEFAULT: 600000,
  WORKER_POLL_INTERVAL_MS_DEFAULT: 1000,
  WORKER_MAX_CONSECUTIVE_ERRORS_DEFAULT: 5,
  WORKER_MAX_QUERIES_PER_TASK_DEFAULT: 10,
  WORKER_CRON_RUN_WINDOW_MS_DEFAULT: 3600000,
  WORKER_POST_TASK_DELAY_MS_DEFAULT: 30000,
  HEALTH_CHECK_TIMEOUT_MS_DEFAULT: 5000,

  // Graph & Memory
  GRAPH_SIMILARITY_THRESHOLD_DEFAULT: 0.8,
  GRAPH_MAX_PATH_HOPS_DEFAULT: 5,
  MEMORY_RETRIES_DEFAULT: 3,
  MEMORY_RETRY_WAIT_MULTIPLIER_DEFAULT: 1000,

  // LLM Constraints
  LLM_MAX_BUFFER_BYTES_DEFAULT: 10485760,
  LLM_DEFAULT_TIMEOUT_MS_DEFAULT: 45000,
  LLM_CONCURRENCY_LIMIT_DEFAULT: 3,

  // Guidance
  GUIDANCE_MAX_ZIPS_DEFAULT: 1000,
  GUIDANCE_MIN_SIMILARITY_DEFAULT: 0.72,
  GUIDANCE_MAX_CHUNK_CHARS_DEFAULT: 2000,
  GUIDANCE_MAX_FILE_CHARS_DEFAULT: 120000,

  // Budgets
  USER_BUDGET_DEFAULT: 12,
  CRON_BUDGET_DEFAULT: 6,
  CRON_RUN_BUDGET_DEFAULT: 30,

  // Snapshots
  GRAPH_SNAPSHOT_MAX_ENTITIES_DEFAULT: 1000,
  GRAPH_SNAPSHOT_MAX_RELATIONS_DEFAULT: 2000,
  GRAPH_SNAPSHOT_MAX_COMMUNITIES_DEFAULT: 100,

  // Hooks & Scripts
  AUTOMATION_ENABLED_DEFAULT: true,
  BACKGROUND_WORKER_ENABLED_DEFAULT: true,
  HOOKS_ENABLED_DEFAULT: true,
  QWEN_SCRIPT_DEFAULT: 'scripts/qwen',
  QWEN_MODEL_DEFAULT: 'mlx-community/Qwen3-14B-4bit',
  HOOK_FILE_CHANGED_DEBOUNCE_MS_DEFAULT: 10000,
  HOOK_ACTION_TIMEOUT_SEC_DEFAULT_DEFAULT: 120,
  HOOK_ACTION_TIMEOUT_SEC_MAX_DEFAULT: 900,
  HOOK_EXECUTION_CACHE_SIZE_DEFAULT: 2000,

  // KnowFlow LLM Queue
  LLM_MAX_CONCURRENCY_DEFAULT: 1,
  LLM_QUEUE_TIMEOUT_MS_DEFAULT: 900000,
  LLM_QUEUE_NAME_DEFAULT: 'local-llm',

  // Memory Loop
  MEMORY_LOOP_ALLOW_CLOUD_DEFAULT: false,
  MEMORY_LOOP_DEFAULT_ALIAS_DEFAULT: 'gemma4',
  MEMORY_LOOP_LIGHT_ALIAS_DEFAULT: 'bonsai',
  MEMORY_LOOP_INTERVAL_MS_DEFAULT: 300000,
  MEMORY_LOOP_MAX_LOCAL_RETRIES_DEFAULT: 1,
  MEMORY_LOOP_MIN_QUALITY_SCORE_DEFAULT: 0.5,
  MEMORY_LOOP_IDLE_BACKOFF_MULTIPLIER_DEFAULT: 2,
  MEMORY_LOOP_MAX_INTERVAL_MS_DEFAULT: 900000,
} as const;
