import { generateEntityId } from '../utils/entityId.js';

export type TechnologyConcept = {
  id: string;
  name: string;
  tags: string[];
  description: string;
  patterns: RegExp[];
  languages?: string[];
};

export type TechnologyApplicability = {
  technologies: string[];
  languages: string[];
  tags: string[];
};

export type TechnologyConceptRelation = {
  sourceName: string;
  targetName: string;
  relationType: string;
  weight: number;
  confidence: number;
};

const concept = (input: Omit<TechnologyConcept, 'id'>): TechnologyConcept => ({
  id: generateEntityId('concept', input.name),
  ...input,
});

const uniqueStrings = (values: string[]): string[] =>
  values.filter((value, index, all) => value.length > 0 && all.indexOf(value) === index);

export const TECHNOLOGY_CONCEPTS: TechnologyConcept[] = [
  concept({
    name: 'TypeScript',
    tags: ['technology', 'language', 'typescript'],
    description:
      'TypeScript language and ecosystem rules, including typing, tsconfig, schema validation, and TypeScript-oriented tooling.',
    patterns: [
      /typescript/i,
      /\btsx?\b/i,
      /tsconfig/i,
      /interface/i,
      /unknown/i,
      /\bany\b/i,
      /import\.meta\.env/i,
      /jsdoc/i,
      /@src|@components|@lib|@logger/i,
    ],
    languages: ['TypeScript'],
  }),
  concept({
    name: 'JavaScript',
    tags: ['technology', 'language', 'javascript'],
    description: 'JavaScript language and runtime practices for browser and Node.js projects.',
    patterns: [/javascript/i, /\bjsx\b/i, /\bjs\b/i, /ecmascript/i, /\bnpm\b/i],
    languages: ['JavaScript'],
  }),
  concept({
    name: 'Java',
    tags: ['technology', 'language', 'java'],
    description: 'Java language and JVM backend development practices.',
    patterns: [/\bjava\b/i, /\bjvm\b/i, /maven/i, /gradle/i, /spring/i],
    languages: ['Java'],
  }),
  concept({
    name: 'Rust',
    tags: ['technology', 'language', 'rust'],
    description: 'Rust language practices, Cargo projects, ownership, traits, and systems code.',
    patterns: [/\brust\b/i, /cargo/i, /crate/i, /borrow checker/i, /trait/i],
    languages: ['Rust'],
  }),
  concept({
    name: 'Cargo',
    tags: ['technology', 'tooling', 'cargo', 'rust'],
    description:
      'Cargo package management, build, workspace, and test practices for Rust projects.',
    patterns: [/cargo/i, /cargo\.toml/i, /cargo\.lock/i],
    languages: ['Rust'],
  }),
  concept({
    name: 'Clippy',
    tags: ['technology', 'linting', 'clippy', 'rust'],
    description: 'Clippy linting practices for Rust correctness, style, and maintainability.',
    patterns: [/clippy/i, /cargo clippy/i],
    languages: ['Rust'],
  }),
  concept({
    name: 'rustfmt',
    tags: ['technology', 'formatting', 'rustfmt', 'rust'],
    description: 'rustfmt formatting practices for Rust code style consistency.',
    patterns: [/rustfmt/i, /cargo fmt/i],
    languages: ['Rust'],
  }),
  concept({
    name: 'Tokio',
    tags: ['technology', 'async-runtime', 'tokio', 'rust'],
    description:
      'Tokio async runtime practices for Rust network services and concurrent workloads.',
    patterns: [/tokio/i],
    languages: ['Rust'],
  }),
  concept({
    name: 'Axum',
    tags: ['technology', 'framework', 'web', 'axum', 'rust'],
    description: 'Axum web framework practices for Rust HTTP APIs and services.',
    patterns: [/axum/i],
    languages: ['Rust'],
  }),
  concept({
    name: 'Actix Web',
    tags: ['technology', 'framework', 'web', 'actix-web', 'rust'],
    description: 'Actix Web framework practices for Rust HTTP APIs and services.',
    patterns: [/actix[- ]web/i, /actix_web/i],
    languages: ['Rust'],
  }),
  concept({
    name: 'Serde',
    tags: ['technology', 'serialization', 'serde', 'rust'],
    description: 'Serde serialization and deserialization practices for Rust data models.',
    patterns: [/serde/i, /serialize/i, /deserialize/i],
    languages: ['Rust'],
  }),
  concept({
    name: 'SQLx',
    tags: ['technology', 'database', 'sqlx', 'rust'],
    description: 'SQLx database access and compile-time checked query practices for Rust.',
    patterns: [/sqlx/i],
    languages: ['Rust'],
  }),
  concept({
    name: 'Python',
    tags: ['technology', 'language', 'python'],
    description: 'Python language practices for application, automation, and data workflows.',
    patterns: [/\bpython\b/i, /\bpyproject\b/i, /\bpip\b/i, /\bpytest\b/i, /\bpoetry\b/i],
    languages: ['Python'],
  }),
  concept({
    name: 'NumPy',
    tags: ['technology', 'library', 'numeric', 'numpy', 'python'],
    description: 'NumPy numerical array and vectorized computation practices for Python.',
    patterns: [/numpy/i, /\bnp\./i],
    languages: ['Python'],
  }),
  concept({
    name: 'pandas',
    tags: ['technology', 'library', 'dataframe', 'pandas', 'python'],
    description: 'pandas dataframe, data cleaning, and tabular analysis practices for Python.',
    patterns: [/pandas/i, /\bpd\./i, /dataframe/i],
    languages: ['Python'],
  }),
  concept({
    name: 'SciPy',
    tags: ['technology', 'library', 'scientific-computing', 'scipy', 'python'],
    description:
      'SciPy scientific computing, optimization, signal processing, and statistics practices.',
    patterns: [/scipy/i],
    languages: ['Python'],
  }),
  concept({
    name: 'Pydantic',
    tags: ['technology', 'validation', 'pydantic', 'python'],
    description: 'Pydantic data validation and settings modeling practices for Python.',
    patterns: [/pydantic/i, /basemodel/i],
    languages: ['Python'],
  }),
  concept({
    name: 'FastAPI',
    tags: ['technology', 'framework', 'web', 'fastapi', 'python'],
    description: 'FastAPI web API framework practices for Python services.',
    patterns: [/fastapi/i],
    languages: ['Python'],
  }),
  concept({
    name: 'Django',
    tags: ['technology', 'framework', 'web', 'django', 'python'],
    description:
      'Django web framework practices for Python applications and admin-backed services.',
    patterns: [/django/i],
    languages: ['Python'],
  }),
  concept({
    name: 'Flask',
    tags: ['technology', 'framework', 'web', 'flask', 'python'],
    description: 'Flask web framework practices for Python APIs and lightweight applications.',
    patterns: [/flask/i],
    languages: ['Python'],
  }),
  concept({
    name: 'SQLAlchemy',
    tags: ['technology', 'orm', 'sqlalchemy', 'python'],
    description: 'SQLAlchemy ORM and SQL toolkit practices for Python database access.',
    patterns: [/sqlalchemy/i],
    languages: ['Python'],
  }),
  concept({
    name: 'pytest',
    tags: ['technology', 'testing', 'pytest', 'python'],
    description: 'pytest unit and integration testing practices for Python projects.',
    patterns: [/pytest/i],
    languages: ['Python'],
  }),
  concept({
    name: 'Ruff',
    tags: ['technology', 'linting', 'formatting', 'ruff', 'python'],
    description: 'Ruff linting and formatting practices for Python projects.',
    patterns: [/ruff/i],
    languages: ['Python'],
  }),
  concept({
    name: 'Black',
    tags: ['technology', 'formatting', 'black', 'python'],
    description: 'Black formatting practices for Python code style consistency.',
    patterns: [/\bblack\b/i],
    languages: ['Python'],
  }),
  concept({
    name: 'mypy',
    tags: ['technology', 'type-checking', 'mypy', 'python'],
    description: 'mypy static type checking practices for Python projects.',
    patterns: [/mypy/i],
    languages: ['Python'],
  }),
  concept({
    name: 'Poetry',
    tags: ['technology', 'package-manager', 'poetry', 'python'],
    description: 'Poetry dependency management, packaging, and pyproject practices for Python.',
    patterns: [/poetry/i, /poetry\.lock/i],
    languages: ['Python'],
  }),
  concept({
    name: 'Go',
    tags: ['technology', 'language', 'go', 'golang'],
    description: 'Go language practices for services, CLIs, and concurrent systems.',
    patterns: [/\bgolang\b/i, /\bgo\b/i, /go\.mod/i, /goroutine/i, /go test/i],
    languages: ['Go'],
  }),
  concept({
    name: 'C#',
    tags: ['technology', 'language', 'csharp', 'dotnet'],
    description: 'C# and .NET application development practices.',
    patterns: [/\bc#\b/i, /\bcsharp\b/i, /\.net/i, /dotnet/i, /asp\.net/i],
    languages: ['C#'],
  }),
  concept({
    name: 'Kotlin',
    tags: ['technology', 'language', 'kotlin'],
    description: 'Kotlin language practices for JVM, Android, and server-side projects.',
    patterns: [/\bkotlin\b/i, /ktor/i, /android/i],
    languages: ['Kotlin'],
  }),
  concept({
    name: 'Swift',
    tags: ['technology', 'language', 'swift'],
    description: 'Swift language practices for Apple platform development.',
    patterns: [/\bswift\b/i, /swiftui/i, /xcode/i],
    languages: ['Swift'],
  }),
  concept({
    name: 'PHP',
    tags: ['technology', 'language', 'php'],
    description: 'PHP language and backend application practices.',
    patterns: [/\bphp\b/i, /composer/i, /laravel/i, /symfony/i],
    languages: ['PHP'],
  }),
  concept({
    name: 'Ruby',
    tags: ['technology', 'language', 'ruby'],
    description: 'Ruby language and Rails application practices.',
    patterns: [/\bruby\b/i, /rails/i, /gemfile/i, /bundler/i],
    languages: ['Ruby'],
  }),
  concept({
    name: 'Node.js',
    tags: ['technology', 'runtime', 'nodejs', 'javascript', 'typescript'],
    description: 'Node.js runtime practices for backend services, CLIs, and tooling.',
    patterns: [/node\.?js/i, /\bnode\b/i, /\bnpm\b/i, /package\.json/i],
    languages: ['TypeScript', 'JavaScript'],
  }),
  concept({
    name: 'Bun',
    tags: ['technology', 'runtime', 'bun', 'javascript', 'typescript'],
    description: 'Bun runtime, package manager, test runner, and JavaScript/TypeScript tooling.',
    patterns: [/\bbun\b/i, /bun\.lockb/i, /bunfig/i],
    languages: ['TypeScript', 'JavaScript'],
  }),
  concept({
    name: 'React',
    tags: ['technology', 'frontend', 'react'],
    description: 'React UI implementation rules and related hook/component practices.',
    patterns: [/react/i, /\buse[A-Z][A-Za-z0-9]*\b/, /usequery/i, /useoptimistic/i],
    languages: ['TypeScript', 'JavaScript'],
  }),
  concept({
    name: 'Vue',
    tags: ['technology', 'frontend', 'vue'],
    description: 'Vue application and component development practices.',
    patterns: [/\bvue\b/i, /nuxt/i, /composition api/i],
    languages: ['TypeScript', 'JavaScript'],
  }),
  concept({
    name: 'Svelte',
    tags: ['technology', 'frontend', 'svelte'],
    description: 'Svelte and SvelteKit application development practices.',
    patterns: [/svelte/i, /sveltekit/i],
    languages: ['TypeScript', 'JavaScript'],
  }),
  concept({
    name: 'Next.js',
    tags: ['technology', 'frontend', 'nextjs', 'react'],
    description:
      'Next.js application practices including routing, server components, and rendering.',
    patterns: [/next\.?js/i, /server component/i, /app router/i],
    languages: ['TypeScript', 'JavaScript'],
  }),
  concept({
    name: 'Tauri',
    tags: ['technology', 'desktop', 'tauri', 'rust'],
    description: 'Tauri desktop integration and Rust backend communication rules.',
    patterns: [/tauri/i],
    languages: ['Rust', 'TypeScript'],
  }),
  concept({
    name: 'Zod',
    tags: ['technology', 'validation', 'zod', 'typescript'],
    description: 'Zod schema validation and schema-first TypeScript data modeling.',
    patterns: [/zod/i, /schema-first/i],
    languages: ['TypeScript'],
  }),
  concept({
    name: 'TanStack Query',
    tags: ['technology', 'frontend', 'tanstack-query', 'react', 'typescript'],
    description:
      'TanStack Query rules for query keys, invalidation, cache, mutation, and fetch flow.',
    patterns: [/tanstack/i, /react query/i, /usequery/i, /queryclient/i, /query key/i],
    languages: ['TypeScript', 'JavaScript'],
  }),
  concept({
    name: 'Biome',
    tags: ['technology', 'tooling', 'biome', 'typescript', 'javascript'],
    description: 'Biome formatting and linting rules for TypeScript and JavaScript projects.',
    patterns: [/biome/i],
    languages: ['TypeScript', 'JavaScript'],
  }),
  concept({
    name: 'ESLint',
    tags: ['technology', 'tooling', 'eslint', 'typescript', 'javascript'],
    description: 'ESLint linting rules and static analysis configuration.',
    patterns: [/eslint/i],
    languages: ['TypeScript', 'JavaScript'],
  }),
  concept({
    name: 'i18next',
    tags: ['technology', 'i18next', 'i18n'],
    description: 'i18next internationalization rules for UI text and locale management.',
    patterns: [/i18next/i, /i18n/i, /国際化|多言語/i],
    languages: ['TypeScript', 'JavaScript'],
  }),
  concept({
    name: 'Terraform',
    tags: ['technology', 'infrastructure', 'terraform', 'iac'],
    description:
      'Terraform infrastructure-as-code practices for provisioning and module management.',
    patterns: [/terraform/i, /terraforma/i, /\btfstate\b/i, /\bhcl\b/i, /infrastructure as code/i],
  }),
  concept({
    name: 'GitHub Actions',
    tags: ['technology', 'ci', 'github-actions', 'automation'],
    description: 'GitHub Actions workflow automation and CI/CD practices.',
    patterns: [
      /github actions/i,
      /\.github\/workflows/i,
      /workflow_dispatch/i,
      /\bactions\/checkout\b/i,
    ],
  }),
  concept({
    name: 'CI/CD',
    tags: ['technology', 'ci', 'cd', 'delivery', 'automation'],
    description:
      'Continuous integration and delivery practices across build, test, deploy, and release flows.',
    patterns: [
      /\bci\/cd\b/i,
      /\bcicd\b/i,
      /continuous integration/i,
      /continuous delivery/i,
      /pipeline/i,
    ],
  }),
  concept({
    name: 'Docker',
    tags: ['technology', 'container', 'docker'],
    description: 'Docker container build, runtime, and compose practices.',
    patterns: [/docker/i, /dockerfile/i, /docker compose/i],
  }),
  concept({
    name: 'Kubernetes',
    tags: ['technology', 'container', 'kubernetes', 'k8s'],
    description:
      'Kubernetes orchestration practices for workloads, services, and cluster operations.',
    patterns: [/kubernetes/i, /\bk8s\b/i, /helm/i, /kubectl/i],
  }),
  concept({
    name: 'AWS',
    tags: ['technology', 'cloud', 'aws'],
    description: 'AWS cloud architecture, infrastructure, and service operation practices.',
    patterns: [/\baws\b/i, /amazon web services/i, /\bs3\b/i, /lambda/i, /cloudformation/i],
  }),
  concept({
    name: 'Azure',
    tags: ['technology', 'cloud', 'azure'],
    description:
      'Azure cloud architecture, identity, infrastructure, and service operation practices.',
    patterns: [/\bazure\b/i, /\bmsal\b/i, /entra id/i, /azure functions/i],
  }),
  concept({
    name: 'Google Cloud',
    tags: ['technology', 'cloud', 'gcp', 'google-cloud'],
    description: 'Google Cloud architecture, infrastructure, and service operation practices.',
    patterns: [/\bgcp\b/i, /google cloud/i, /cloud run/i, /bigquery/i],
  }),
  concept({
    name: 'PostgreSQL',
    tags: ['technology', 'database', 'postgresql', 'postgres'],
    description: 'PostgreSQL database schema, query, extension, and operational practices.',
    patterns: [/postgresql/i, /postgres/i, /\bpsql\b/i, /pgvector/i],
  }),
  concept({
    name: 'MySQL',
    tags: ['technology', 'database', 'mysql'],
    description: 'MySQL database schema, query, and operational practices.',
    patterns: [/mysql/i, /mariadb/i],
  }),
  concept({
    name: 'SQLite',
    tags: ['technology', 'database', 'sqlite'],
    description: 'SQLite embedded database schema, query, and migration practices.',
    patterns: [/sqlite/i],
  }),
  concept({
    name: 'Redis',
    tags: ['technology', 'database', 'cache', 'redis'],
    description: 'Redis cache, queue, and ephemeral data structure practices.',
    patterns: [/redis/i],
  }),
  concept({
    name: 'Prisma',
    tags: ['technology', 'orm', 'prisma', 'typescript'],
    description: 'Prisma ORM schema, migration, and query practices.',
    patterns: [/prisma/i],
    languages: ['TypeScript', 'JavaScript'],
  }),
  concept({
    name: 'Drizzle ORM',
    tags: ['technology', 'orm', 'drizzle', 'typescript'],
    description: 'Drizzle ORM schema, migration, and type-safe query practices.',
    patterns: [/drizzle/i],
    languages: ['TypeScript'],
  }),
  concept({
    name: 'Vitest',
    tags: ['technology', 'testing', 'vitest', 'typescript', 'javascript'],
    description: 'Vitest unit and integration testing practices.',
    patterns: [/vitest/i],
    languages: ['TypeScript', 'JavaScript'],
  }),
  concept({
    name: 'Jest',
    tags: ['technology', 'testing', 'jest', 'typescript', 'javascript'],
    description: 'Jest unit and integration testing practices.',
    patterns: [/jest/i],
    languages: ['TypeScript', 'JavaScript'],
  }),
  concept({
    name: 'Playwright',
    tags: ['technology', 'testing', 'e2e', 'playwright'],
    description: 'Playwright browser automation and end-to-end testing practices.',
    patterns: [/playwright/i],
    languages: ['TypeScript', 'JavaScript'],
  }),
  concept({
    name: 'Testing Library',
    tags: ['technology', 'testing', 'frontend', 'testing-library'],
    description: 'Testing Library practices for user-centered frontend tests.',
    patterns: [/testing-library/i, /@testing-library/i],
    languages: ['TypeScript', 'JavaScript'],
  }),
  concept({
    name: 'OAuth',
    tags: ['technology', 'auth', 'oauth', 'security'],
    description: 'OAuth and OpenID Connect authentication and authorization practices.',
    patterns: [/oauth/i, /openid connect/i, /\boidc\b/i],
  }),
  concept({
    name: 'MSAL',
    tags: ['technology', 'auth', 'msal', 'azure'],
    description: 'MSAL authentication practices for Microsoft identity integrations.',
    patterns: [/msal/i],
    languages: ['TypeScript', 'JavaScript'],
  }),
];

export const inferTechnologyApplicability = (text: string): TechnologyApplicability => {
  const concepts = TECHNOLOGY_CONCEPTS.filter((concept) =>
    concept.patterns.some((pattern) => pattern.test(text)),
  );
  const technologies = uniqueStrings(concepts.map((concept) => concept.name));
  const languages = uniqueStrings(concepts.flatMap((concept) => concept.languages ?? []));
  const tags = uniqueStrings(concepts.flatMap((concept) => concept.tags));
  return { technologies, languages, tags };
};

export const TECHNOLOGY_CONCEPT_RELATIONS: TechnologyConceptRelation[] = [
  {
    sourceName: 'TypeScript',
    targetName: 'JavaScript',
    relationType: 'builds_on_technology',
    weight: 1.2,
    confidence: 0.95,
  },
  {
    sourceName: 'Node.js',
    targetName: 'JavaScript',
    relationType: 'runtime_for_technology',
    weight: 1.1,
    confidence: 0.95,
  },
  {
    sourceName: 'Node.js',
    targetName: 'TypeScript',
    relationType: 'runtime_for_technology',
    weight: 0.9,
    confidence: 0.85,
  },
  {
    sourceName: 'Bun',
    targetName: 'JavaScript',
    relationType: 'runtime_for_technology',
    weight: 1.1,
    confidence: 0.95,
  },
  {
    sourceName: 'Bun',
    targetName: 'TypeScript',
    relationType: 'runtime_for_technology',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'Bun',
    targetName: 'Node.js',
    relationType: 'alternative_runtime_to',
    weight: 0.8,
    confidence: 0.8,
  },
  {
    sourceName: 'React',
    targetName: 'JavaScript',
    relationType: 'framework_for_technology',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'React',
    targetName: 'TypeScript',
    relationType: 'framework_for_technology',
    weight: 0.9,
    confidence: 0.85,
  },
  {
    sourceName: 'Next.js',
    targetName: 'React',
    relationType: 'builds_on_technology',
    weight: 1.1,
    confidence: 0.95,
  },
  {
    sourceName: 'Vue',
    targetName: 'JavaScript',
    relationType: 'framework_for_technology',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'Svelte',
    targetName: 'JavaScript',
    relationType: 'framework_for_technology',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'Zod',
    targetName: 'TypeScript',
    relationType: 'tooling_for_technology',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'TanStack Query',
    targetName: 'React',
    relationType: 'tooling_for_technology',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'Biome',
    targetName: 'TypeScript',
    relationType: 'tooling_for_technology',
    weight: 0.95,
    confidence: 0.9,
  },
  {
    sourceName: 'Biome',
    targetName: 'JavaScript',
    relationType: 'tooling_for_technology',
    weight: 0.95,
    confidence: 0.9,
  },
  {
    sourceName: 'ESLint',
    targetName: 'TypeScript',
    relationType: 'tooling_for_technology',
    weight: 0.9,
    confidence: 0.85,
  },
  {
    sourceName: 'ESLint',
    targetName: 'JavaScript',
    relationType: 'tooling_for_technology',
    weight: 0.95,
    confidence: 0.9,
  },
  {
    sourceName: 'Vitest',
    targetName: 'TypeScript',
    relationType: 'testing_for_technology',
    weight: 0.9,
    confidence: 0.85,
  },
  {
    sourceName: 'Vitest',
    targetName: 'JavaScript',
    relationType: 'testing_for_technology',
    weight: 0.9,
    confidence: 0.85,
  },
  {
    sourceName: 'Jest',
    targetName: 'JavaScript',
    relationType: 'testing_for_technology',
    weight: 0.9,
    confidence: 0.85,
  },
  {
    sourceName: 'Playwright',
    targetName: 'JavaScript',
    relationType: 'testing_for_technology',
    weight: 0.85,
    confidence: 0.8,
  },
  {
    sourceName: 'Testing Library',
    targetName: 'React',
    relationType: 'testing_for_technology',
    weight: 0.9,
    confidence: 0.85,
  },
  {
    sourceName: 'Tauri',
    targetName: 'Rust',
    relationType: 'bridges_technology',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'Tauri',
    targetName: 'TypeScript',
    relationType: 'bridges_technology',
    weight: 0.85,
    confidence: 0.8,
  },
  {
    sourceName: 'Cargo',
    targetName: 'Rust',
    relationType: 'package_manager_for_technology',
    weight: 1.1,
    confidence: 0.95,
  },
  {
    sourceName: 'Clippy',
    targetName: 'Rust',
    relationType: 'tooling_for_technology',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'rustfmt',
    targetName: 'Rust',
    relationType: 'tooling_for_technology',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'Tokio',
    targetName: 'Rust',
    relationType: 'async_runtime_for_technology',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'Axum',
    targetName: 'Rust',
    relationType: 'framework_for_technology',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'Axum',
    targetName: 'Tokio',
    relationType: 'builds_on_technology',
    weight: 0.9,
    confidence: 0.85,
  },
  {
    sourceName: 'Actix Web',
    targetName: 'Rust',
    relationType: 'framework_for_technology',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'Serde',
    targetName: 'Rust',
    relationType: 'serialization_for_technology',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'SQLx',
    targetName: 'Rust',
    relationType: 'database_for_technology',
    weight: 0.9,
    confidence: 0.85,
  },
  {
    sourceName: 'NumPy',
    targetName: 'Python',
    relationType: 'library_for_technology',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'pandas',
    targetName: 'Python',
    relationType: 'library_for_technology',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'pandas',
    targetName: 'NumPy',
    relationType: 'builds_on_technology',
    weight: 0.75,
    confidence: 0.75,
  },
  {
    sourceName: 'SciPy',
    targetName: 'NumPy',
    relationType: 'builds_on_technology',
    weight: 0.85,
    confidence: 0.85,
  },
  {
    sourceName: 'Pydantic',
    targetName: 'Python',
    relationType: 'validation_for_technology',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'FastAPI',
    targetName: 'Python',
    relationType: 'framework_for_technology',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'FastAPI',
    targetName: 'Pydantic',
    relationType: 'builds_on_technology',
    weight: 0.9,
    confidence: 0.85,
  },
  {
    sourceName: 'Django',
    targetName: 'Python',
    relationType: 'framework_for_technology',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'Flask',
    targetName: 'Python',
    relationType: 'framework_for_technology',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'SQLAlchemy',
    targetName: 'Python',
    relationType: 'orm_for_technology',
    weight: 0.95,
    confidence: 0.9,
  },
  {
    sourceName: 'pytest',
    targetName: 'Python',
    relationType: 'testing_for_technology',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'Ruff',
    targetName: 'Python',
    relationType: 'tooling_for_technology',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'Black',
    targetName: 'Python',
    relationType: 'tooling_for_technology',
    weight: 0.9,
    confidence: 0.85,
  },
  {
    sourceName: 'mypy',
    targetName: 'Python',
    relationType: 'tooling_for_technology',
    weight: 0.95,
    confidence: 0.9,
  },
  {
    sourceName: 'Poetry',
    targetName: 'Python',
    relationType: 'package_manager_for_technology',
    weight: 0.95,
    confidence: 0.9,
  },
  {
    sourceName: 'Prisma',
    targetName: 'TypeScript',
    relationType: 'orm_for_technology',
    weight: 0.9,
    confidence: 0.85,
  },
  {
    sourceName: 'Drizzle ORM',
    targetName: 'TypeScript',
    relationType: 'orm_for_technology',
    weight: 0.9,
    confidence: 0.85,
  },
  {
    sourceName: 'PostgreSQL',
    targetName: 'Drizzle ORM',
    relationType: 'used_by_technology',
    weight: 0.75,
    confidence: 0.75,
  },
  {
    sourceName: 'PostgreSQL',
    targetName: 'Prisma',
    relationType: 'used_by_technology',
    weight: 0.75,
    confidence: 0.75,
  },
  {
    sourceName: 'GitHub Actions',
    targetName: 'CI/CD',
    relationType: 'implements_technology_practice',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'Docker',
    targetName: 'CI/CD',
    relationType: 'supports_technology_practice',
    weight: 0.75,
    confidence: 0.75,
  },
  {
    sourceName: 'Kubernetes',
    targetName: 'Docker',
    relationType: 'orchestrates_technology',
    weight: 0.85,
    confidence: 0.8,
  },
  {
    sourceName: 'Terraform',
    targetName: 'AWS',
    relationType: 'provisions_technology',
    weight: 0.85,
    confidence: 0.8,
  },
  {
    sourceName: 'Terraform',
    targetName: 'Azure',
    relationType: 'provisions_technology',
    weight: 0.85,
    confidence: 0.8,
  },
  {
    sourceName: 'Terraform',
    targetName: 'Google Cloud',
    relationType: 'provisions_technology',
    weight: 0.85,
    confidence: 0.8,
  },
  {
    sourceName: 'MSAL',
    targetName: 'Azure',
    relationType: 'auth_for_technology',
    weight: 1,
    confidence: 0.9,
  },
  {
    sourceName: 'OAuth',
    targetName: 'MSAL',
    relationType: 'standard_used_by_technology',
    weight: 0.8,
    confidence: 0.8,
  },
];
