import type { FailureKnowledgeSource } from './types.js';

export const seedKnowledge: FailureKnowledgeSource = {
  goldenPaths: [
    {
      id: 'gp-cache-invalidation-mutation-001',
      title: 'Mutation after cache update',
      pathType: 'mutation_cache_update',
      appliesWhen: [
        'state-changing mutation is added or changed',
        'UI depends on cached query data',
      ],
      requiredSteps: [
        'identify the affected query key',
        'invalidate or update the affected query key on success',
      ],
      allowedAlternatives: ['setQueryData updates the affected cache', 'project-standard refresh'],
      blockWhenMissing: ['invalidate or update the affected query key on success'],
      severityWhenMissing: 'warning',
      riskSignals: ['cache_invalidation', 'external_api_error'],
      languages: ['typescript', 'javascript', 'svelte'],
      frameworks: ['React', 'Svelte', 'SvelteKit'],
      tags: ['failure-firewall', 'golden-path', 'cache_invalidation'],
      status: 'active',
      source: 'seed',
    },
    {
      id: 'gp-auth-permission-guard-preserved-001',
      title: 'Auth and permission guard preserved',
      pathType: 'auth_permission_guard_preserved',
      appliesWhen: ['auth, middleware, guard, token, or permission logic changes'],
      requiredSteps: [
        'preserve or strengthen the authorization boundary',
        'include a test or explicit rationale when guard conditions are relaxed',
      ],
      allowedAlternatives: [
        'equivalent upstream guard is added',
        'policy is enforced in middleware',
      ],
      blockWhenMissing: ['preserve or strengthen the authorization boundary'],
      severityWhenMissing: 'error',
      riskSignals: ['auth', 'permission'],
      languages: ['typescript', 'javascript'],
      frameworks: [],
      tags: ['failure-firewall', 'golden-path', 'auth', 'permission'],
      status: 'active',
      source: 'seed',
    },
    {
      id: 'gp-destructive-db-operation-scoped-001',
      title: 'Destructive DB operation is scoped',
      pathType: 'destructive_db_operation_scoped',
      appliesWhen: ['delete, truncate, drop, or destructive migration is added or changed'],
      requiredSteps: [
        'scope destructive operations by tenant, user, project, or explicit key',
        'make rollback or recovery assumptions visible',
      ],
      allowedAlternatives: [
        'migration is explicitly reversible',
        'operation is guarded by dry-run',
      ],
      blockWhenMissing: ['scope destructive operations by tenant, user, project, or explicit key'],
      severityWhenMissing: 'error',
      riskSignals: ['deletion', 'destructive_db_change', 'migration', 'db_schema_change'],
      languages: ['typescript', 'javascript', 'sql'],
      frameworks: [],
      tags: ['failure-firewall', 'golden-path', 'database'],
      status: 'active',
      source: 'seed',
    },
    {
      id: 'gp-multi-write-transaction-boundary-001',
      title: 'Multi-write operation has transaction boundary',
      pathType: 'multi_write_transaction_boundary',
      appliesWhen: ['multiple persistent writes happen in the same use case'],
      requiredSteps: [
        'consider a transaction boundary for multiple persistent writes',
        'document rollback or compensation behavior',
      ],
      allowedAlternatives: ['writes are independent and retry-safe', 'compensation is explicit'],
      blockWhenMissing: ['consider a transaction boundary for multiple persistent writes'],
      severityWhenMissing: 'warning',
      riskSignals: ['transaction', 'db_schema_change'],
      languages: ['typescript', 'javascript', 'sql'],
      frameworks: [],
      tags: ['failure-firewall', 'golden-path', 'transaction'],
      status: 'active',
      source: 'seed',
    },
    {
      id: 'gp-schema-validation-kept-in-sync-001',
      title: 'Schema validation kept in sync',
      pathType: 'schema_validation_kept_in_sync',
      appliesWhen: ['API input, schema, or request handling changes'],
      requiredSteps: [
        'update validation schema with input shape changes',
        'keep error mapping and tests aligned',
      ],
      allowedAlternatives: ['input is validated by an equivalent project-standard schema'],
      blockWhenMissing: ['update validation schema with input shape changes'],
      severityWhenMissing: 'warning',
      riskSignals: ['input_validation', 'db_schema_change'],
      languages: ['typescript', 'javascript'],
      frameworks: [],
      tags: ['failure-firewall', 'golden-path', 'validation'],
      status: 'active',
      source: 'seed',
    },
  ],
  failurePatterns: [
    {
      id: 'ff-cache-invalidation-mutation-001',
      title: 'Missing cache invalidation after mutation',
      patternType: 'missing_cache_invalidation',
      severity: 'error',
      riskSignals: ['cache_invalidation', 'external_api_error'],
      languages: ['typescript', 'javascript', 'svelte'],
      frameworks: ['React', 'Svelte', 'SvelteKit'],
      matchHints: ['mutation function changes persistent state', 'no invalidation in success path'],
      requiredEvidence: [
        'mutation-like code changed',
        'cache update call is absent in added lines',
      ],
      goldenPathId: 'gp-cache-invalidation-mutation-001',
      status: 'active',
      falsePositiveCount: 0,
      source: 'seed',
    },
    {
      id: 'ff-auth-guard-weakened-001',
      title: 'Auth guard weakened without compensating check',
      patternType: 'auth_guard_weakened',
      severity: 'error',
      riskSignals: ['auth', 'permission'],
      languages: ['typescript', 'javascript'],
      frameworks: [],
      matchHints: ['guard condition changed', 'test or alternative guard is missing'],
      requiredEvidence: ['auth or permission code changed'],
      goldenPathId: 'gp-auth-permission-guard-preserved-001',
      status: 'active',
      falsePositiveCount: 0,
      source: 'seed',
    },
    {
      id: 'ff-destructive-db-without-scope-001',
      title: 'Destructive database operation lacks scope',
      patternType: 'destructive_db_without_scope',
      severity: 'error',
      riskSignals: ['deletion', 'destructive_db_change', 'migration'],
      languages: ['typescript', 'javascript', 'sql'],
      frameworks: [],
      matchHints: ['delete, truncate, or drop is present', 'where or tenant scope is absent'],
      requiredEvidence: ['destructive database operation changed'],
      goldenPathId: 'gp-destructive-db-operation-scoped-001',
      status: 'active',
      falsePositiveCount: 0,
      source: 'seed',
    },
    {
      id: 'ff-schema-validation-gap-001',
      title: 'Input handling changed without validation update',
      patternType: 'schema_validation_gap',
      severity: 'warning',
      riskSignals: ['input_validation'],
      languages: ['typescript', 'javascript'],
      frameworks: [],
      matchHints: ['handler or schema changed', 'validation call is absent'],
      requiredEvidence: ['input handling changed'],
      goldenPathId: 'gp-schema-validation-kept-in-sync-001',
      status: 'active',
      falsePositiveCount: 0,
      source: 'seed',
    },
  ],
};
